# Generated by Django 3.1 on 2020-08-28 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chr10Aafr',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr10aAFR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr10Aamr',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr10aAMR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr10Aeas',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr10aEAS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr10Aeur',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr10aEUR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr11Aafr',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr11aAFR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr11Aamr',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr11aAMR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr11Aeas',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr11aEAS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr11Aeur',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr11aEUR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr12Aafr',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr12aAFR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr12Aamr',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr12aAMR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr12Aeas',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr12aEAS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr12Aeur',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr12aEUR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr13Aafr',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr13aAFR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr13Aamr',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr13aAMR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr13Aeas',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr13aEAS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr13Aeur',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr13aEUR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr14Aafr',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr14aAFR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr14Aamr',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr14aAMR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr14Aeas',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr14aEAS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr14Aeur',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr14aEUR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr15Aafr',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr15aAFR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr15Aamr',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr15aAMR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr15Aeas',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr15aEAS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr15Aeur',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr15aEUR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr16Aafr',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr16aAFR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr16Aamr',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr16aAMR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr16Aeas',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr16aEAS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr16Aeur',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr16aEUR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr17Aafr',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr17aAFR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr17Aamr',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr17aAMR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr17Aeas',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr17aEAS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr17Aeur',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr17aEUR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr18Aafr',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr18aAFR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr18Aamr',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr18aAMR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr18Aeas',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr18aEAS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr18Aeur',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr18aEUR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr19Aafr',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr19aAFR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr19Aamr',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr19aAMR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr19Aeas',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr19aEAS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr19Aeur',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr19aEUR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr1Aafr',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr1aAFR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr1Aamr',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr1aAMR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr1Aeas',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr1aEAS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr1Aeur',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr1aEUR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr20Aafr',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr20aAFR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr20Aamr',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr20aAMR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr20Aeas',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr20aEAS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr20Aeur',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr20aEUR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr21Aafr',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr21aAFR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr21Aamr',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr21aAMR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr21Aeas',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr21aEAS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr21Aeur',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr21aEUR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr22Aafr',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr22aAFR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr22Aamr',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr22aAMR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr22Aeas',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr22aEAS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr22Aeur',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr22aEUR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr2Aafr',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr2aAFR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr2Aamr',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr2aAMR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr2Aeas',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr2aEAS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr2Aeur',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr2aEUR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr3Aafr',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr3aAFR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr3Aamr',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr3aAMR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr3Aeas',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr3aEAS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr3Aeur',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr3aEUR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr4Aafr',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr4aAFR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr4Aamr',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr4aAMR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr4Aeas',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr4aEAS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr4Aeur',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr4aEUR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr5Aafr',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr5aAFR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr5Aamr',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr5aAMR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr5Aeas',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr5aEAS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr5Aeur',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr5aEUR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr6Aafr',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr6aAFR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr6Aamr',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr6aAMR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr6Aeas',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr6aEAS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr6Aeur',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr6aEUR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr7Aafr',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr7aAFR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr7Aamr',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr7aAMR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr7Aeas',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr7aEAS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr7Aeur',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr7aEUR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr8Aafr',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr8aAFR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr8Aamr',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr8aAMR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr8Aeas',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr8aEAS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr8Aeur',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr8aEUR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr9Aafr',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr9aAFR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr9Aamr',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr9aAMR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr9Aeas',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr9aEAS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chr9Aeur',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chr9aEUR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chrxaafr',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chrXaAFR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chrxaamr',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chrXaAMR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chrxaeas',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chrXaEAS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chrxaeur',
            fields=[
                ('stop1', models.IntegerField(primary_key=True, serialize=False)),
                ('stop2', models.IntegerField()),
                ('r2', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chrXaEUR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gwascatalog',
            fields=[
                ('first_author', models.CharField(blank=True, max_length=100, null=True)),
                ('published_data', models.CharField(blank=True, max_length=11, null=True)),
                ('study_accession', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('chromosome', models.CharField(max_length=4)),
                ('position', models.CharField(max_length=20)),
                ('disease_trait', models.CharField(blank=True, max_length=225, null=True)),
                ('super_population', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'gwascatalog',
                'managed': False,
            },
        ),
    ]
